### ISSUE TITLE
Misc unprioritized TODO list for v0 prototype

### ISSUE THREAD

**Issue by afourney** [microsoft/FLAML#1046]
- [ ] Document API endpoints
- [ ] Add API endpoints for setting user-bio and other settings
- [ ] Harden API endpoints for all user inputs (input sanitization)
- [ ] Do something smarter with overly-long chats (it currently just prints an error)
- [ ] Catch all errors when handling API calls, and pass to client in appropriate JSON  objects
- [ ] Clean up Agent code in preparation for supporting different agents
- [ ] Support multiple agent implementations.
- [ ] Allow specification of different agents when starting a conversation. 
- [ ] Update Browser Plugin to post papers, and host plugin on the webpage
- [ ] Enable users to add/upload papers
- [ ] Allow users to list and continue conversations
