### ISSUE TITLE
Agent Implementation of MathChat

### ISSUE THREAD

**Issue by yiranwu0** [microsoft/FLAML#1066]
Implement the [MathChat paper](https://arxiv.org/abs/2306.01337) with the current agent framework:
- Put the specified math problem-solving prompt in system message of `AssistantAgent` for the LLM. If the behavior is not desired, the assistant agent need to be modified to accept this prompt in user message.
- Implement a `MathUserProxyAgent` from `UserProxyAgent`, need to inherit the `autoreply` function.
- MathChat proposes a conversational framework to solve math problems, which is equivalent to interactions between the two agents. Building on the agents also allow human inputs.
```[tasklist]
### Tasks
- [x] Review PR https://github.com/microsoft/FLAML/pull/1056
- [x] Evaluate the performance of AssistantAgent and UserProxyAgent on math problem solving (on several representative problems)
- [ ] Agent implementation of MathChat. PR made and approvals from reviewers pending in https://github.com/microsoft/FLAML/pull/1076
- [ ] Update arxiv: Update link to implementation(keep the old one for the purpose of reproducing the exp results)
- [ ] Update FLAML's autogen documentation: mention MathChat
- [ ] Write a blogpost about MathChat
```

**Comment by kevin666aa** [comment]
> 

I mean that when calling the AssistantAgent, I will not use the default system_message but input one. I will implement a corresponding MathUserProxyAgent, and I will modify the `autoreply` function. It will follow the working design, however the autoreply will be very different from the base proxyagent.

**Comment by qingyun-wu** [comment]
@kevin666aa, I revised the task list.
