### ISSUE TITLE
Improve logging in oai

### ISSUE THREAD

**Issue by sonichi** [microsoft/FLAML#1069]
Currently, the oai package has an experimental support for logging: https://microsoft.github.io/FLAML/docs/Use-Cases/Auto-Generation#logging-experimental
The data are logged in memory as a dictionary. This feature needs to be improved to persist the log automatically and support log analytics, and support #1063 .

```[tasklist]
### Tasks
- [ ] Check whether the data format needs to be changed.
- [ ] Choose a logging solution. For example, mlflow.
- [ ] Write documentation and test.
- [ ] Implement.
- [ ] Write a notebook example.
```
