### ISSUE TITLE
Support new OpenAI models

### ISSUE THREAD

**Issue by sonichi** [microsoft/FLAML#1081]
https://openai.com/blog/function-calling-and-other-api-updates

```[tasklist]
### Tasks
- [x] New model names
- [x] Update price
- [x] Update search space if needed
- [x] Process function_call responses
- [x] Add test to function_call
- [ ] https://github.com/microsoft/FLAML/issues/1083
```
