### ISSUE TITLE
Build a pipeline, to output adversarial examples from given input examples and input LLM config to solve the problem

### ISSUE THREAD

**Issue by sonichi** [microsoft/FLAML#1103]
https://github.com/microsoft/FLAML/blob/7808b4f6a4156d88baba32411a25e69bde12d43a/flaml/autogen/math/baseline_PoT.py#L115-L123
https://github.com/microsoft/FLAML/blob/7808b4f6a4156d88baba32411a25e69bde12d43a/flaml/autogen/math/baseline_PoT.py#L148C1-L152C17

```[tasklist]
### Tasks
- [ ] replace config_list with the azure_end_point config_list
- [x] change the output to make it work in component
- [x] end-to-end pipeline
```
