### ISSUE TITLE
HistGradientBoosting support

### ISSUE THREAD

**Issue by glevv** [microsoft/FLAML#868]
Right now it could be only added by writing custom class.

Question is: will there be added support to `flamlize_estimator` for `HistGradientBoostingClassifier` and `HistGradientBoostingRegressor` ?
```[tasklist]
### Tasks
- [x] Implement a custom estimator following
- [x] Add test to make sure it works as intended
- [x] Make a subpackage automl.contrib and include the newly created estimators in it
- [x] Add a section "contributed estimators" in the documentation website: https://microsoft.github.io/FLAML/docs/Use-Cases/Task-Oriented-AutoML#estimator
- [x] Change the test to use the newly added estimators
```

**Comment by sonichi** [comment]
There is no such plan as far as I know. If you'd like to work on it, I can help with guidance.

**Comment by glevv** [comment]
I'm returning to this issue. Can you please help me with the process of adding HistGradientBoosting estimator?

**Comment by sonichi** [comment]
Sure. Just to clarify, do you want it to be 
1. a built-in _tunable_ estimator in `AutoML.fit` such that you can use something like `estimator_list=["histgb"]` to perform tuning, or
2. a built-in _zero-shot_ estimator such that you can import using `from flaml import HistGradientBoostingClassifier` and use a data-dependent HP configuration for a new dataset without tuning?

2 needs more work than 1. `flamlize_estimator` is used for 2.

**Comment by glevv** [comment]
Let's go with 1st option for now. As I understand 2nd could be added later on top of 1

**Comment by sonichi** [comment]
Right. For option 1, I'd suggest the following steps.

1. Implement a custom estimator following https://microsoft.github.io/FLAML/docs/Use-Cases/Task-Oriented-AutoML#guidelines-on-tuning-a-custom-estimator.
2. Add test to make sure it works as intended.
3. Make a subpackage `automl.contrib` and include the newly created estimators in it.
4. Change the test to use the newly added estimators.
5. Add a section "contributed estimators" in the documentation website: https://microsoft.github.io/FLAML/docs/Use-Cases/Task-Oriented-AutoML#estimator.

**Comment by glevv** [comment]
And as I understand, for option 2 I will need to run extensive HPO on selected datasets and save best hyperparameters to `deafult/histgb/*.json` ?

**Comment by sonichi** [comment]
Yes. That's right. Is your PR still blocked by the time series forecasting test error?

**Comment by glevv** [comment]
There were no commits to main after that, so the tests are still failing
